### PR TITLE
New iterator released: mixed Cartesian product

### PR DESCRIPTION
**Pull request by hoxnox**
Hi. I released new iterator for the library. I called it mixed product. See README, examples and tests. Hope it would be usefull.

### CODE REVIEW

**Comment by ryanhaining** [comment]
Hi! Thanks for contributing. I'll look through this more thoroughly when I can, hopefully tonight or tomorrow. At  glance I'm confused by the example output in the README edit. `"up"` never prints? Can you verify the output is right? thanks.

**Comment by hoxnox** [comment]
It's just a little part of the answer - there is ellipsis.
4 мая 2016 г. 19:02 пользователь "Ryan Haining" <notifications@github.com>
написал:

**Comment by ryanhaining** [comment]
I'm seeing this as being the same output as `product` but in a different order. If I replace all the `ResType` alias to be `multiset` instead of `vector`, then replace every call to `mixed_product` with a call to `product`, your test file still passes.

**Comment by hoxnox** [comment]
Yes. The output is same as product, but in different order. It was the main point.
It's not very easy when you have only forward iterators, low memory and don't want the situation when the values are repeated from step to step.

Example:
file1 - 50MB
file2 - 50MB
I have machine with 512MB and want line-by-line Cartesian project of these files. But  I don't want to repeat lines from step to step. So I have to move every iterator - in the first file and in the second.

**Comment by aldanor** [comment]
Nit: there's no such thing as a "Cartesian project".

**Comment by dnbaker** [comment]
@aldanor -- sure, it was a typo, but [this paper](http://www.sciencedirect.com/science/article/pii/0191659995000663) begs to differ.

**Comment by aldanor** [comment]
@dnbaker ^ in the context of mathematics and algorithms, that is...

**Comment by dnbaker** [comment]
It's just a funny. That's all! :)

**Pull request closed without merging**
